// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuAU1KI4YFacX0-LEOjCzXs301Dp9qFGU',
    appId: '1:778031503453:web:9a5a93380d627d135215b4',
    messagingSenderId: '778031503453',
    projectId: 'chatter-cfe01',
    authDomain: 'chatter-cfe01.firebaseapp.com',
    storageBucket: 'chatter-cfe01.firebasestorage.app',
    measurementId: 'G-T8XQF62XQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaStMH2ds2n-H1e3ZMedXFXOC0jcZJ9L0',
    appId: '1:778031503453:android:224a2515daf404555215b4',
    messagingSenderId: '778031503453',
    projectId: 'chatter-cfe01',
    storageBucket: 'chatter-cfe01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9gMff7UNyqAnTDG54MXj48B7XCH2hEMg',
    appId: '1:778031503453:ios:8648f730b8c86d955215b4',
    messagingSenderId: '778031503453',
    projectId: 'chatter-cfe01',
    storageBucket: 'chatter-cfe01.firebasestorage.app',
    iosBundleId: 'com.naserebedo.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9gMff7UNyqAnTDG54MXj48B7XCH2hEMg',
    appId: '1:778031503453:ios:8648f730b8c86d955215b4',
    messagingSenderId: '778031503453',
    projectId: 'chatter-cfe01',
    storageBucket: 'chatter-cfe01.firebasestorage.app',
    iosBundleId: 'com.naserebedo.chatter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuAU1KI4YFacX0-LEOjCzXs301Dp9qFGU',
    appId: '1:778031503453:web:09eb7bd1acb1f8f35215b4',
    messagingSenderId: '778031503453',
    projectId: 'chatter-cfe01',
    authDomain: 'chatter-cfe01.firebaseapp.com',
    storageBucket: 'chatter-cfe01.firebasestorage.app',
    measurementId: 'G-55456N2SE3',
  );
}
